// Roughly frequency-ordered English words. Earlier = more common.
// Used by the predictor: a word's unigram score derives from its index here.
export const UNIGRAMS = [
  "the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as",
  "you","do","at","this","but","his","by","from","they","we","say","her","she","or","an",
  "will","my","one","all","would","there","their","what","so","up","out","if","about","who",
  "get","which","go","me","when","make","can","like","time","no","just","him","know","take",
  "people","into","year","your","good","some","could","them","see","other","than","then","now",
  "look","only","come","its","over","think","also","back","after","use","two","how","our",
  "work","first","well","way","even","new","want","because","any","these","give","day","most",
  "us","is","are","was","were","been","being","am","i","im","dont","cant","wont","ive","ill",
  "really","right","great","little","much","need","feel","love","life","world","help","please",
  "thank","thanks","hello","okay","yes","yeah","sure","maybe","today","tomorrow","tonight",
  "morning","night","home","house","school","friend","family","mom","dad","name","place",
  "thing","something","nothing","everything","anything","someone","everyone","nobody","here",
  "where","why","again","always","never","sometimes","often","very","too","more","less","many",
  "few","big","small","long","short","high","low","old","young","next","last","early","late",
  "open","close","start","stop","keep","let","put","find","found","tell","told","ask","asked",
  "call","called","try","tried","leave","left","move","play","run","walk","talk","read","write",
  "hear","listen","speak","watch","show","turn","bring","happen","become","change","believe",
  "hold","mean","follow","stand","lose","pay","meet","include","continue","set","learn","seem",
  "great","important","different","following","without","before","through","between","under",
  "around","during","while","against","both","another","such","same","own","each","every",
  "water","food","money","word","number","part","child","children","woman","man","men","women",
  "book","story","question","answer","problem","idea","reason","point","fact","hand","eye",
  "head","face","side","area","room","door","car","city","country","state","group","company",
  "system","program","game","line","end","member","power","minute","week","month","hour",
  "morning","afternoon","evening","weekend","summer","winter","spring","wait","stay","sit",
  "remember","forget","understand","wonder","guess","hope","wish","care","mind","heart","kind",
  "able","sorry","welcome","goodbye","alright","awesome","cool","nice","fine","fun","happy",
  "ready","done","busy","tired","hungry","glad","afraid","sure","true","real","whole","full",
  "free","easy","hard","best","better","worse","worst","least","quite","almost","enough",
  "together","along","across","behind","beyond","inside","outside","above","below","near","far"
].filter((w, i, a) => a.indexOf(w) === i);

// Most-likely next words given a previous word (hand-tuned, lowercase).
export const BIGRAMS = {
  "i": ["am","have","will","was","think","dont","want","need","can","like","would","know","feel","just","really"],
  "im": ["going","not","sure","here","just","so","really","glad","sorry"],
  "the": ["same","first","other","most","best","world","way","time","end","fact","day","next","last"],
  "to": ["be","the","do","go","get","make","see","have","know","take","help","find"],
  "a": ["lot","few","little","good","new","great","while","bit","man","day","friend"],
  "is": ["a","the","not","it","very","going","that","this","so","really"],
  "was": ["a","the","not","just","very","going","so"],
  "of": ["the","a","course","this","my","them","all","us","it"],
  "in": ["the","a","my","this","fact","order","front","time"],
  "you": ["are","have","can","will","want","know","should","need","think","like","get"],
  "and": ["the","i","then","a","it","so","we","they","that"],
  "it": ["is","was","will","has","would","can","does","might","really"],
  "this": ["is","was","will","one","time","week","year","place"],
  "that": ["is","was","the","i","you","we","they","would","will"],
  "we": ["are","have","will","can","were","should","need","could","did"],
  "for": ["the","a","you","me","this","your","us","them","it"],
  "have": ["a","to","been","the","you","not","some","my","never"],
  "be": ["a","the","able","here","there","fine","okay","back","good"],
  "with": ["the","a","you","me","my","us","them","that"],
  "on": ["the","a","my","your","it","this","time"],
  "are": ["you","the","not","going","so","really","we"],
  "my": ["name","friend","life","mom","dad","house","family","day","heart"],
  "so": ["much","i","that","we","you","far","good","many"],
  "what": ["is","are","do","you","the","time","about","happened"],
  "how": ["are","do","much","many","to","about","long","old"],
  "do": ["you","not","the","it","that","this"],
  "dont": ["know","want","think","have","worry","care","like"],
  "can": ["you","i","be","we","not","help","do"],
  "will": ["be","you","not","the","have","make"],
  "there": ["is","are","was","will","were","might"],
  "they": ["are","were","have","will","had","said","want"],
  "he": ["is","was","has","will","had","said","would"],
  "she": ["is","was","has","will","had","said","would"],
  "would": ["be","you","like","have","love","never"],
  "about": ["the","it","you","this","that","time"],
  "all": ["the","of","right","my","day","year"],
  "when": ["you","i","the","we","they","it"],
  "your": ["name","life","time","house","family","day"],
  "thank": ["you"],
  "thanks": ["for","so","a"],
  "good": ["morning","night","day","luck","job","idea","time"],
  "see": ["you","the","what","it","that"],
  "let": ["me","us","them","it","go"],
  "going": ["to","on","back","home","out"],
  "want": ["to","a","the","you","some","it"],
  "need": ["to","a","you","some","help","more"],
  "really": ["like","want","need","good","appreciate","love","dont"],
};
